### ISSUE TITLE
Blog post: Highlight how WASH web and openwashdata relate to each other

### ISSUE THREAD

**Issue by larnsce** [openwashdata-dev/openwashdata#15]
## Background

- Discussed idea with @nickdickinson and Merel during meeting on 2023-08-29
- Cross-post on openwashdata blog and https://washweb.org/ 

```[tasklist]
### Tasks
- [ ] Prepare an outline of blog pot
- [ ] Decide on structure and word limits for blog post
- [ ] Decide on publishing date
```

Tag: @mianzg

**Comment by nickdickinson** [comment]
@larnsce I will work on a draft of the short blog post with Merel @merellaauwen from our side with some headings to use as an outline. I don't think the size is going to be enough to require too formal of an approach. If you're ok with that then you can add/change things after.

**Comment by larnsce** [comment]
@nickdickinson, we are starting to prepare for the newsletter that will contain a blog.  We are doing the blog every second month for now and the publication date for a newsletter with blog is 5th December. 

Should we aim for that?

**Comment by nickdickinson** [comment]
@merellaawuen is preparing the blog (can you add her to this issue?). We also have a washweb.org introduction blog that we will post first and infrastructure to set up. Aiming for 5th of December newsletter is perfect. Are you ok with us already posting something before that on washweb.org? Maybe good to let the news trickle out anyway.

**Comment by larnsce** [comment]
Thanks for the update. I have just added @merellaauwen as a contributor to this repository. 

Yes, totally fine to already post on washweb.org. We would then re-post it on our blog.

I have added a Partners page to our website. A deploy preview is here: https://deploy-preview-32--luminous-treacle-bd685b.netlify.app/pages/partners/

I had hoped to integrate this under "About", but cannot figure out how to split listing content within a page.

Please everything and let me know what you would like to be changed:

- [ ] logo
- [ ] title
- [ ] subtitlt
- [ ] description of WASH Web

**Comment by merellaauwen** [comment]
Thanks for adding me here! I'm working on the draft blog post and can share it with you by the end of this week. As for the partnerships page, great to be featured - just a few changes: 

logo (for now): 
![WASHWeb_logo](https://github.com/openwashdata-dev/openwashdata/assets/124254075/078b7144-60e0-44e4-8c47-98447e94e29b)

subtitle: making WASH information discoverable, representative, and useful  

description: WASH Web is a set of participatory initiatives to give you and everyone you know better access to water, sanitation and hygiene (WASH) information. WASH Web is made up of people and organizations that work to fill WASH gap to make data discoverable, usable and representative. WASH Web is meant to serve as an open platform and requires diverse inputs to work.

new LinkedIn page: https://www.linkedin.com/company/washweb/

@nickdickinson please check if I'm missing anything / would like to change the wording

**Comment by larnsce** [comment]
Thank you, @merellaauwen. I have finally put your changes into place.

https://openwashdata.org/pages/partners/washweb/

We will probably announce this partnership in our upcoming Newsletter issue on Monday, 6th November. @mianzg 

Let me know if you would rather not have it highlighted yet.

**Comment by mianzg** [comment]
@merellaauwen @larnsce @nickdickinson should we aim to include a blog post for December newsletter?

**Comment by merellaauwen** [comment]
@mianzg @larnsce @nickdickinson please find the blogpost for the Feb 6th newsletter attached in Quarto format. Feel free to adapt the text where you see fit!
[20240130_washweb_openwashdata_blog1.qmd.zip](https://github.com/openwashdata-dev/openwashdata/files/14111750/20240130_washweb_openwashdata_blog1.qmd.zip)

**Comment by larnsce** [comment]
Thank you, @merellaauwen. I will integrate it like this in our blog on openwashdata.org. 

Could you also share the image "JMP%20Data%20usage%20v2.png" please?

**Comment by larnsce** [comment]
@merellaauwen, I have transfered your `.qmd` into the Quarto blog post format and prepared a pull request from which we get a deploy preview:

- https://deploy-preview-40--luminous-treacle-bd685b.netlify.app/pages/blog/

Could you please do the following:

- [ ] Check if your are happy with the links I have added for your name and affiliation
- [ ] Check on the edits that were made by @elizabeth-tilley (https://github.com/openwashdata/website/pull/40/commits/4e93a82f0ab1ac7b223d1d27966c4dd4199aed5f)
- [ ] Share the screenshot with me that is shown for the jmpwashdata package
- [ ] Prepare a short description of the blog post, which will then be shown in the overview (I had thought we could also use the first paragraph)

**Comment by larnsce** [comment]
Thank you, @merellaauwen. The blog post is live now. We will share it through our newsletter today.

https://openwashdata.org/pages/blog/posts/2024-02-02-washweb/

**Comment by merellaauwen** [comment]
Thank you - ours is live now too: https://washweb.org/posts/20231006%20openwashdata_washweb/

Just making a few final cosmetic changes to the website.
